server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10
    password: 123123
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/securitydb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # 配置spring session存储
  session:
    store-type: none
mybatis:
  type-aliases-package: com.winston.domain
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    default-fetch-size: 100
# spring security是否启动
security:
  basic:
    enabled: true

# 自定义登录页
winston:
  security:
    # 浏览器HTML请求的配置
    browser:
      # 配置登录页
#      loginPage: /demo-signIn.html
      # 配置请求类型,一半前后端分离配置JSON,网页配置REDIRECT
      loginType: REDIRECT
    # 图片验证码配置
    code:
      image:
        length: 6
        width: 100
        # 需要做图形验证码校验的URL
        url: /user,/user/*
